
#ifndef LLA_READERS_IDONDEMAND_API_H
#define LLA_READERS_IDONDEMAND_API_H

#ifdef IDONDEMANDREADERS_STATIC_DEFINE
#  define LLA_READERS_IDONDEMAND_API
#  define IDONDEMANDREADERS_NO_EXPORT
#else
#  ifndef LLA_READERS_IDONDEMAND_API
#    ifdef idondemandreaders_EXPORTS
        /* We are building this library */
#      define LLA_READERS_IDONDEMAND_API __declspec(dllexport)
#    else
        /* We are using this library */
#      define LLA_READERS_IDONDEMAND_API __declspec(dllimport)
#    endif
#  endif

#  ifndef IDONDEMANDREADERS_NO_EXPORT
#    define IDONDEMANDREADERS_NO_EXPORT 
#  endif
#endif

#ifndef IDONDEMANDREADERS_DEPRECATED
#  define IDONDEMANDREADERS_DEPRECATED __declspec(deprecated)
#endif

#ifndef IDONDEMANDREADERS_DEPRECATED_EXPORT
#  define IDONDEMANDREADERS_DEPRECATED_EXPORT LLA_READERS_IDONDEMAND_API IDONDEMANDREADERS_DEPRECATED
#endif

#ifndef IDONDEMANDREADERS_DEPRECATED_NO_EXPORT
#  define IDONDEMANDREADERS_DEPRECATED_NO_EXPORT IDONDEMANDREADERS_NO_EXPORT IDONDEMANDREADERS_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef IDONDEMANDREADERS_NO_DEPRECATED
#    define IDONDEMANDREADERS_NO_DEPRECATED
#  endif
#endif

#endif /* LLA_READERS_IDONDEMAND_API_H */
