
#ifndef LLA_READERS_AXESSTMC13_API_H
#define LLA_READERS_AXESSTMC13_API_H

#ifdef AXESSTMC13READERS_STATIC_DEFINE
#  define LLA_READERS_AXESSTMC13_API
#  define AXESSTMC13READERS_NO_EXPORT
#else
#  ifndef LLA_READERS_AXESSTMC13_API
#    ifdef axesstmc13readers_EXPORTS
        /* We are building this library */
#      define LLA_READERS_AXESSTMC13_API __declspec(dllexport)
#    else
        /* We are using this library */
#      define LLA_READERS_AXESSTMC13_API __declspec(dllimport)
#    endif
#  endif

#  ifndef AXESSTMC13READERS_NO_EXPORT
#    define AXESSTMC13READERS_NO_EXPORT 
#  endif
#endif

#ifndef AXESSTMC13READERS_DEPRECATED
#  define AXESSTMC13READERS_DEPRECATED __declspec(deprecated)
#endif

#ifndef AXESSTMC13READERS_DEPRECATED_EXPORT
#  define AXESSTMC13READERS_DEPRECATED_EXPORT LLA_READERS_AXESSTMC13_API AXESSTMC13READERS_DEPRECATED
#endif

#ifndef AXESSTMC13READERS_DEPRECATED_NO_EXPORT
#  define AXESSTMC13READERS_DEPRECATED_NO_EXPORT AXESSTMC13READERS_NO_EXPORT AXESSTMC13READERS_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef AXESSTMC13READERS_NO_DEPRECATED
#    define AXESSTMC13READERS_NO_DEPRECATED
#  endif
#endif

#endif /* LLA_READERS_AXESSTMC13_API_H */
