
#ifndef LLA_READERS_AXESSTMCLEGIC_API_H
#define LLA_READERS_AXESSTMCLEGIC_API_H

#ifdef AXESSTMCLEGICREADERS_STATIC_DEFINE
#  define LLA_READERS_AXESSTMCLEGIC_API
#  define AXESSTMCLEGICREADERS_NO_EXPORT
#else
#  ifndef LLA_READERS_AXESSTMCLEGIC_API
#    ifdef axesstmclegicreaders_EXPORTS
        /* We are building this library */
#      define LLA_READERS_AXESSTMCLEGIC_API __declspec(dllexport)
#    else
        /* We are using this library */
#      define LLA_READERS_AXESSTMCLEGIC_API __declspec(dllimport)
#    endif
#  endif

#  ifndef AXESSTMCLEGICREADERS_NO_EXPORT
#    define AXESSTMCLEGICREADERS_NO_EXPORT 
#  endif
#endif

#ifndef AXESSTMCLEGICREADERS_DEPRECATED
#  define AXESSTMCLEGICREADERS_DEPRECATED __declspec(deprecated)
#endif

#ifndef AXESSTMCLEGICREADERS_DEPRECATED_EXPORT
#  define AXESSTMCLEGICREADERS_DEPRECATED_EXPORT LLA_READERS_AXESSTMCLEGIC_API AXESSTMCLEGICREADERS_DEPRECATED
#endif

#ifndef AXESSTMCLEGICREADERS_DEPRECATED_NO_EXPORT
#  define AXESSTMCLEGICREADERS_DEPRECATED_NO_EXPORT AXESSTMCLEGICREADERS_NO_EXPORT AXESSTMCLEGICREADERS_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef AXESSTMCLEGICREADERS_NO_DEPRECATED
#    define AXESSTMCLEGICREADERS_NO_DEPRECATED
#  endif
#endif

#endif /* LLA_READERS_AXESSTMCLEGIC_API_H */
